---
- name: k8s check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - community.kubernetes

  tasks:
    - name: Ensure the demo Namespace exists.
      k8s:
        api_version: v1
        kind: Namespace
        name: demo
        state: present

    - name: Create Deployment
      k8s:
        state: present
        wait: true
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: demo
            labels:
              app: nginx
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                - name: nginx
                  image: nginx:1.14.2
                  ports:
                  - containerPort: 80
    - name: Create Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx
            namespace: demo
          spec:
            selector:
              app: nginx
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80