---
- name: info
  hosts: localhost
  gather_facts: true
  connection: local

  tasks:
  - name: Print Job ID
    debug:
      msg: '{{ tower_job_id }}'
  
  - name: Print Workflow Job ID
    debug: 
      msg: '{{ tower_workflow_job_id }}'
  
  - name: Pausing for a few seconds
    pause:
      seconds: 30

  - name: Pring Workflow Job ID Name
    debug: 
      msg: '{{ tower_workflow_job_name }}'
