---
- name: namespace check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - community.kubernetes

  tasks:
    - name: print config file contet b64
      debug:
        msg:
          - "{{ config_data }}"
    - name: print content
      debug:
        msg:
          - "{{ config_data | b64decode }}"