---
- name: namespace check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - ibm.cloudcollection
    - community.kubernetes
  
  environment:
    - IC_API_KEY: "{{ ibmcloud_api_key }}"

  tasks:
    - name: Save Cluster config File
      ibm_container_cluster_config_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        cluster_name_id: "{{cluster_info.id}}"
      register: config_output

    - name: save cluster config path as fact
      set_fact:
        cacheable: True
        cluster_config: "{{ config_output.resource }}"
      when: config_output.rc==0     
    
    - name: Ensure the myapp Namespace exists.
      k8s:
        kubeconfig: "{{ cluster_config.config_file_path }}"
        api_version: v1
        kind: Namespace
        name: myapp
        state: present
      when: config_output.rc==0
