---
- name: namespace check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - community.kubernetes

  tasks:
    - name: print config file contet b64
      debug:
        msg:
          - "{{ config_data }}"
    - name: print content
      debug:
        msg:
          - "{{ config_data | b64decode }}"
    - name: Make sure destination dir exists
      file:
        path: "{{ config_file_path | dirname }}"
        state: directory
        recurse: yes
    - name: write content to file
      copy:
        dest: "{{ config_file_path }}"
        content: "{{ config_data | b64decode }}"
    - name: Ensure the myapp Namespace exists.
      environment:
        KUBECONFIG: "{{ config_file_path }}"
      k8s:
        api_version: v1
        kind: Namespace
        name: myapp
        state: present
