---
- name: namespace check
  hosts: localhost
  gather_facts: true
  connection: local

  collections:
    - community.kubernetes
    
  tasks:
    - name: Ensure the myapp Namespace exists.
      k8s:
        kubeconfig: "{{ config_file_path }}"
        api_version: v1
        kind: Namespace
        name: magic
        state: present
